# 서버 설정
server:
  port: 8080  # 애플리케이션이 실행될 포트

# 데이터베이스 설정
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edunetric  # 데이터베이스 URL
    username: edunetric  # 데이터베이스 사용자 이름
    password: eduedu23@  # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # JDBC 드라이버

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 자동으로 DB 스키마를 업데이트 (개발 중에는 update, 운영에는 validate나 none 사용 권장)
    show-sql: true  # 실행된 SQL 쿼리를 콘솔에 출력

# 로깅 설정
logging:
  level:
    root: info  # 전체 로깅 레벨 설정 (debug, info, warn, error 등)
    com.yourpackage: debug  # 특정 패키지에 대한 로깅 레벨 설정

# CORS 설정
cors:
  allowed-origins: "http://localhost:3000"  # 허용할 프론트엔드 도메인
  allowed-methods: "GET, POST, PUT, DELETE"  # 허용할 HTTP 메서드

## 파일 업로드 설정
#file:
#  upload:
#    dir: /path/to/upload/directory  # 파일 업로드 디렉터리 설정